/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Child */

#ifndef _Included_Child
#define _Included_Child
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Child
 * Method:    m2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Child_m2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
